Q_TITLE="Falco: custom rules, output fields with nanoseconds, scale offenders to 0"
Q_TAGS="cluster files"
Q14_NS=falco-lab
Q14_IMG=falcosecurity/falco-no-driver:latest
# Falco's kernel driver can't run in kind, so detection itself is pre-recorded as
# an alert log. What IS graded for real: your rule file (validated by a real
# falco binary), the output fields, and the cluster end-state.

q_setup() {
  local d; d=$(labdir q14)
  # setup is a fresh start: discard any collected log from a previous attempt
  rm -f "$d/falco.log"
  kq create ns "$Q14_NS"
  for n in web-frontend api-backend; do kq -n "$Q14_NS" delete deploy "$n"; done
  k -n "$Q14_NS" create deployment web-frontend --image=httpd:2.4 >/dev/null 2>&1
  k -n "$Q14_NS" create deployment api-backend  --image=nginx:1.27 >/dev/null 2>&1
  k -n "$Q14_NS" create deployment cache-layer  --image=redis:7 >/dev/null 2>&1
  k -n "$Q14_NS" scale deploy web-frontend api-backend cache-layer --replicas=1 >/dev/null 2>&1

  # base macros/lists the custom file depends on (stands in for falco_rules.yaml)
  cat > "$d/falco_rules.yaml" <<'EOF'
# Trimmed stand-in for /etc/falco/falco_rules.yaml -- provides the shared
# lists/macros that rules in rules.d/ reference. Do not edit this file.
- list: package_mgmt_binaries
  items: [dpkg, dpkg-preconfigu, rpm, rpmkey, yum, "apt", apt-get, aptitude, apk, dnf, zypper]

- macro: package_mgmt_procs
  condition: (proc.name in (package_mgmt_binaries))

- macro: open_write
  condition: (evt.type in (open,openat,openat2) and evt.is_open_write=true and fd.typechar='f')

- macro: container
  condition: (container.id != host)
EOF
  cat > "$d/falco_custom.yaml" <<'EOF'
# Stands in for /etc/falco/rules.d/falco_custom.yaml
# EDIT THIS FILE.

- rule: Write below etc
  desc: Detect any write below /etc
  condition: open_write and fd.name startswith /etc
  output: "File below /etc opened for writing (file=%fd.name container=%container.name image=%container.image.repository pod=%k8s.pod.name)"
  priority: ERROR

- rule: Package management process launched
  desc: Detect package management processes launched in a container
  condition: package_mgmt_procs and container
  output: "Package management process launched (user=%user.name command=%proc.cmdline container_id=%container.id container_name=%container.name image=%container.image.repository)"
  priority: WARNING
EOF
  # pre-recorded alert stream (stands in for live Falco output on the node)
  cat > "$d/falco_alerts.log" <<'EOF'
15:02:11.120043219: Error File below /etc opened for writing (file=/etc/passwd container=web-frontend image=httpd pod=web-frontend-6d4f9c7b85-2xqlv)
15:02:11.330901772: Error File below /etc opened for writing (file=/etc/passwd container=web-frontend image=httpd pod=web-frontend-6d4f9c7b85-2xqlv)
15:02:19.884210017: Warning Package management process launched (user=root command=apk add curl container_id=3f9ad21c0b77 container_name=api-backend image=nginx)
15:02:24.771330948: Warning Package management process launched (user=root command=apk add bash container_id=3f9ad21c0b77 container_name=api-backend image=nginx)
15:02:31.004417290: Notice Redis started by user root (container_name=cache-layer image=redis)
EOF
  cat > "$d/TASK.md" <<EOF
Falco files are in $d :
    falco_rules.yaml    base lists/macros  (DO NOT EDIT -- stands in for /etc/falco/falco_rules.yaml)
    falco_custom.yaml   YOUR rules file    (stands in for /etc/falco/rules.d/falco_custom.yaml)
    falco_alerts.log    a recorded Falco alert stream from this cluster

Namespace "$Q14_NS" has three Deployments: web-frontend (httpd),
api-backend (nginx), cache-layer (redis).

TASK 1 -- From falco_alerts.log, find the pod running image httpd that modifies
          /etc/passwd. Scale ITS Deployment down to 0.

TASK 2 -- Find the pod running image nginx that triggers the rule
          "Package management process launched".
          a) In falco_custom.yaml, change that rule's output so the text AFTER
             "Package management process launched" contains ONLY, in this order:
                 time-with-nanoseconds, container-id, container-name, user-name
          b) Save the alerts for that rule to:
                 $d/falco.log
             (grep them out of falco_alerts.log -- at least 2 lines)
          c) Scale that pod's Deployment down to 0.

Leave cache-layer running.

TRAP: %evt.time.s is the NO-nanoseconds field. The one that includes nanoseconds
is %evt.time (or %evt.time.iso8601). The grader checks this.

Your rule file is validated with a real falco binary, so it must still parse.

Grade with:  ./cks verify 14
EOF
  step "3 deployments created in ns $Q14_NS; files in $d"
}

q_verify() {
  start_checks
  local d="$LAB/q14" cf="$LAB/q14/falco_custom.yaml"
  [ -f "$cf" ] || { no "falco_custom.yaml exists" "./cks reset 14"; report; return; }

  # ---- TASK 1: httpd deployment scaled to 0 ----
  local r
  r=$(k -n "$Q14_NS" get deploy web-frontend -o jsonpath='{.spec.replicas}' 2>/dev/null)
  if [ "$r" = "0" ]; then
    ok "TASK 1: httpd Deployment 'web-frontend' scaled to 0"
  else
    no "TASK 1: httpd Deployment 'web-frontend' scaled to 0" \
       "replicas=${r:-<missing>} -- the /etc/passwd alert names pod web-frontend-... (image httpd)"
  fi

  # ---- TASK 2c: nginx deployment scaled to 0 ----
  r=$(k -n "$Q14_NS" get deploy api-backend -o jsonpath='{.spec.replicas}' 2>/dev/null)
  if [ "$r" = "0" ]; then
    ok "TASK 2c: nginx Deployment 'api-backend' scaled to 0"
  else
    no "TASK 2c: nginx Deployment 'api-backend' scaled to 0" \
       "replicas=${r:-<missing>} -- the package-management alerts name container api-backend (image nginx)"
  fi

  # ---- the innocent one must be untouched ----
  r=$(k -n "$Q14_NS" get deploy cache-layer -o jsonpath='{.spec.replicas}' 2>/dev/null)
  if [ "$r" = "1" ]; then
    ok "cache-layer left running (not an offender)"
  else
    no "cache-layer left running (not an offender)" "replicas=${r:-<missing>} -- only scale down what the alerts implicate"
  fi

  # ---- TASK 2a: the output field edit ----
  local out
  out=$(python3 "$LAB_ROOT/lib/falco_rule_output.py" "$cf" "Package management process launched" 2>/dev/null)
  if [ -z "$out" ]; then
    no "TASK 2a: rule 'Package management process launched' still has an output field" \
       "don't delete the rule or its output:"
  else
    # must keep the prefix
    if printf '%s' "$out" | grep -q 'Package management process launched'; then
      ok "TASK 2a: output keeps the 'Package management process launched' prefix"
    else
      no "TASK 2a: output keeps the 'Package management process launched' prefix" \
         "the task says change the text AFTER that phrase"
    fi
    # strip the prefix, then inspect what remains
    local tail_part
    tail_part=${out#*Package management process launched}
    # nanosecond-capable time field
    if printf '%s' "$tail_part" | grep -qE '%evt\.time\.iso8601|%evt\.time([^.s]|$)|%evt\.time$'; then
      ok "TASK 2a: uses a nanosecond time field (%evt.time / %evt.time.iso8601)"
    elif printf '%s' "$tail_part" | grep -q '%evt\.time\.s'; then
      no "TASK 2a: uses a nanosecond time field" \
         "%evt.time.s is the NO-nanoseconds variant -- use %evt.time"
    else
      no "TASK 2a: uses a nanosecond time field" "no %evt.time* field found in '$tail_part'"
    fi
    printf '%s' "$tail_part" | grep -q '%container\.id'   && ok "TASK 2a: includes %container.id"   || no "TASK 2a: includes %container.id"
    printf '%s' "$tail_part" | grep -q '%container\.name' && ok "TASK 2a: includes %container.name" || no "TASK 2a: includes %container.name"
    printf '%s' "$tail_part" | grep -q '%user\.name'      && ok "TASK 2a: includes %user.name"      || no "TASK 2a: includes %user.name"
    # nothing else
    local extras
    extras=$(printf '%s' "$tail_part" | grep -oE '%[a-zA-Z0-9_.\[\]]+' \
             | grep -vE '^%(evt\.time(\.iso8601)?|container\.id|container\.name|user\.name)$' || true)
    if [ -z "$extras" ]; then
      ok "TASK 2a: output contains ONLY the four requested fields"
    else
      no "TASK 2a: output contains ONLY the four requested fields" "extra field(s): $(printf '%s' "$extras" | tr '\n' ' ')"
    fi
    # order
    local order
    order=$(printf '%s' "$tail_part" | grep -oE '%(evt\.time(\.iso8601)?|container\.id|container\.name|user\.name)' | tr '\n' ' ')
    if printf '%s' "$order" | grep -qE '^%evt\.time(\.iso8601)? +%container\.id +%container\.name +%user\.name *$'; then
      ok "TASK 2a: fields are in the requested order"
    else
      no "TASK 2a: fields are in the requested order" "got: $order"
    fi
  fi

  # ---- rule file must still be valid to a real falco binary ----
  if docker info >/dev/null 2>&1; then
    local vout
    vout=$(docker run --rm -v "$d:/r:ro" --entrypoint falco "$Q14_IMG" \
             --validate /r/falco_rules.yaml --validate /r/falco_custom.yaml 2>&1)
    # "Ok, with warnings" is a pass -- only a real load error is a failure.
    if printf '%s' "$vout" | grep -q 'falco_custom.yaml: Invalid'; then
      local err; err=$(printf '%s' "$vout" | grep -E 'LOAD_ERR|Undefined|Invalid' | head -1)
      no "falco --validate accepts your rule file" "${err:-run the command below to see why}"
      step "to reproduce: docker run --rm -v $d:/r:ro --entrypoint falco $Q14_IMG --validate /r/falco_rules.yaml --validate /r/falco_custom.yaml"
    elif printf '%s' "$vout" | grep -q 'falco_custom.yaml: Ok'; then
      ok "falco --validate accepts your rule file (real falco binary)"
    else
      no "falco --validate accepts your rule file" "unexpected validator output; re-run ./cks reset 14"
    fi
  else
    warn "Docker unavailable, skipping falco --validate"
  fi

  # ---- TASK 2b: collected log ----
  local lf="$d/falco.log"
  if [ ! -s "$lf" ]; then
    no "TASK 2b: $lf exists and is non-empty" "grep the rule's alerts out of falco_alerts.log into falco.log"
  else
    ok "TASK 2b: $lf exists and is non-empty"
    local n; n=$(grep -c 'Package management process launched' "$lf" 2>/dev/null || echo 0)
    [ "$n" -ge 2 ] && ok "TASK 2b: falco.log holds >=2 package-management alerts ($n)" \
      || no "TASK 2b: falco.log holds >=2 package-management alerts" "found $n"
    if grep -qE '[0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{9}' "$lf"; then
      ok "TASK 2b: timestamps in falco.log carry nanoseconds"
    else
      no "TASK 2b: timestamps in falco.log carry nanoseconds" "expected HH:MM:SS.nnnnnnnnn"
    fi
    if grep -q '/etc/passwd' "$lf"; then
      no "TASK 2b: falco.log holds ONLY the package-management rule" "it also contains 'Write below etc' alerts"
    else
      ok "TASK 2b: falco.log holds ONLY the package-management rule"
    fi
  fi
  report
}

q_solve() {
  local d; d=$(labdir q14)
  python3 - "$d/falco_custom.yaml" <<'PY'
import sys,re
p=sys.argv[1]; t=open(p).read()
t=re.sub(r'(- rule: Package management process launched.*?output: )".*?"',
         r'\1"Package management process launched %evt.time, %container.id, %container.name, %user.name"',
         t, flags=re.S)
open(p,'w').write(t)
PY
  grep 'Package management process launched' "$d/falco_alerts.log" > "$d/falco.log"
  k -n "$Q14_NS" scale deploy web-frontend --replicas=0 >/dev/null
  k -n "$Q14_NS" scale deploy api-backend  --replicas=0 >/dev/null
}

q_reset() { kq -n "$Q14_NS" delete deploy --all; q_setup; }
